### ISSUE TITLE
problem not install.

### ISSUE THREAD

**Issue by visaolangle00** [RWPhillips/ObjectAid-Fixed#2]
can you guide us with a video that can be uploaded to youtube, i have tried to install it and it doesn't work, please help us.

**Comment by RWPhillips** [comment]
> can you guide us with a video that can be uploaded to youtube, i have tried to install it and it doesn't work, please help us.

Sure, I can make a video. I'll upload it here in the next day or so.

**Comment by RWPhillips** [comment]
> can you guide us with a video that can be uploaded to youtube, i have tried to install it and it doesn't work, please help us.

Sorry for the long wait. College has kept me really busy!

I have uploaded a quick video on how to install it. It's not a complete 1:1 video on the installation since I have college work that is being done on Eclipse at the moment. Sorry for the video quality, I didn't know my settings were so low on OBS, but eventually I'll make a video to replace this one when I have more time. I was able to follow along with it, so it shouldn't be too bad. Enjoy!

https://youtu.be/T6R4ypbqkvM
